services:
  database:
    container_name: database-akre
    image: redis/redis-stack
    ports:
      - "5379:6379"
      - "5001:8001"
    volumes:
      - ./redis/data:/data
  api:
    container_name: api-akre
    build:
      context: ../
      dockerfile: deployments/api/Dockerfile
    ports:
      - "5080:8080"
    volumes: ['../api:/code']
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      - ROOTUSERNAME=root
      - ROOTPASSWORD=cBMJ6V4HH8djT6zm
    depends_on:
      - database
