services:
  api:
    container_name: api-akre
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    ports:
      - "5000:5000"
    volumes: ['../api:/app']
    environment:
      FLASK_APP: __init__.py
      DATABASE_NAME: akre
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: "KvJ2TyV2"
      DATABASE_HOST: database
  database:
    container_name: database-akre
    image: redis/redis-stack
    ports:
      - "5379:6379"
      - "5001:8001"
    volumes:
      - ./redis/data:/data
    environment:
      MYSQL_ROOT_PASSWORD: "KvJ2TyV2"
      MYSQL_ROOT_HOST: "%"
