# Generated by Django 4.0.6 on 2022-08-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=14)),
                ('endereco_cep', models.CharField(max_length=8)),
                ('endereco_rua', models.CharField(max_length=255)),
                ('endereco_numero', models.CharField(max_length=5)),
                ('endereco_bairro', models.CharField(max_length=255)),
                ('endereco_cidade', models.CharField(max_length=255)),
                ('endereco_uf', models.CharField(max_length=2)),
                ('endereco_complemento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
