# Generated by Django 4.0.6 on 2022-08-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='documento',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
