# Generated by Django 4.0.6 on 2022-08-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='aluguel',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('RESIDENCIAL', 'Residencial (casa, apartamento)'), ('COMERCIAL', 'Comercial (escritório, consultório, comércio)')], default='RESIDENCIAL', max_length=11),
            preserve_default=False,
        ),
    ]
