# Generated by Django 4.0.6 on 2022-08-02 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_imovel_aluguel_imovel_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True)),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_segurado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotacao_taxa', models.DecimalField(decimal_places=4, max_digits=5)),
                ('valor_premio_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotacao_iof_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_premio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('possui_seguro_conteudo', models.BooleanField(default=False)),
                ('possui_resp_civil', models.BooleanField(default=False)),
                ('possui_danos_eletricos', models.BooleanField(default=False)),
                ('possui_seguro_vendaval', models.BooleanField(default=False)),
                ('possui_assistencia', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('fk_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imovel')),
            ],
        ),
    ]
