# Generated by Django 4.0.6 on 2022-08-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='possui_assistencia',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='possui_danos_eletricos',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='possui_resp_civil',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='possui_seguro_conteudo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='possui_seguro_vendaval',
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_assistencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_danos_eletricos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_resp_civil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_seguro_conteudo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_seguro_vendaval',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
